name: Cypress Tests

on: [workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      
      - name: Cypress install, run tests and record
        uses: cypress-io/github-action@v2.9.7
        with:
         runTests: true
         record: true
        env:
          CYPRESS_RECORD_KEY: 87c57539-5522-41fd-8412-9937edeeebfe
